import os
import sys
import glob
import subprocess
import argparse
import shutil

def get_float_input(prompt, default=None):
    while True:
        try:
            val = input(prompt)
            if not val and default is not None:
                return default
            return float(val)
        except ValueError:
            print("有効な数値を入力してください。")

def get_xyz_input(stl_name):
    print(f"\n--- {stl_name} の配置設定 ---")
    x = get_float_input(f"{stl_name} の X方向の移動量 (mm) [デフォルト: 0]: ", 0)
    y = get_float_input(f"{stl_name} の Y方向の移動量 (mm) [デフォルト: 0]: ", 0)
    z = get_float_input(f"{stl_name} の Z方向の移動量 (mm) [デフォルト: 0]: ", 0)
    return x, y, z

def main():
    parser = argparse.ArgumentParser(description="FSAE CFD Setup Wizard")
    parser.add_argument("--no-docker", action="store_true", help="Do not run docker, just prepare files")
    args = parser.parse_args()

    print("==================================================")
    print("      FSAE 簡易CFDシステム Setup Wizard")
    print("==================================================")

    # ディレクトリ準備
    os.makedirs("models", exist_ok=True)
    os.makedirs("logs", exist_ok=True)

    # 1. STLファイルの検出 (全STLを自動検出)
    stl_files = [os.path.basename(f) for f in glob.glob("models/*.stl")]
    aero_stls = [f for f in stl_files if f.lower() not in ["tires.stl", "frame.stl"]]
    if not aero_stls:
        print("エラー: 'models' ディレクトリ内にSTLファイルが見つかりません。")
        print("body.stl などのファイルを 'models/' に配置してから再実行してください。")
        sys.exit(1)

    print("\n検出されたSTL:")
    for f in stl_files:
        print(f"  - {f}")

    use_tires = os.path.exists("models/tires.stl")
    use_frame = os.path.exists("models/frame.stl")

    # 2. 変数の取得
    velocity = get_float_input("\n解析する風速を入力してください (m/s) [デフォルト: 20]: ", 20.0)

    mesh_level = input("メッシュの細かさを選択してください (1:粗い 2:普通 3:細かい) [デフォルト: 2]: ").strip()
    if mesh_level not in ['1', '2', '3']:
        mesh_level = '2'

    clearance = get_float_input("\n全体のグラウンドクリアランス (Z方向の追加移動量 mm) を入力してください [デフォルト: 0]: ", 0)

    # 各STLのオフセット取得
    offsets = {}
    for stl in aero_stls:
        offsets[stl] = get_xyz_input(stl)
    
    if use_tires:
        offsets["tires.stl"] = get_xyz_input("tires.stl")
    
    if use_frame:
        offsets["frame.stl"] = get_xyz_input("frame.stl")

    # 3. setup_stl.sh の生成
    # 単位はメートルに変換 (mm -> m)
    print("\n[システム構築中...]")
    with open("setup_stl.sh", "w") as f:
        f.write("#!/bin/sh\n")
        f.write("# This file is auto-generated by run_cfd.py\n\n")
        f.write("mkdir -p constant/triSurface\n\n")
        
        for stl, (x, y, z) in offsets.items():
            # クリアランスはZに加算してメートル変換
            z_total_m = (z + clearance) / 1000.0
            x_m = x / 1000.0
            y_m = y / 1000.0
            
            f.write(f"echo 'Processing {stl} ...'\n")
            f.write(f"surfaceTransformPoints -translate '({x_m} {y_m} {z_total_m})' ./models/{stl} constant/triSurface/{stl}\n\n")

    os.chmod("setup_stl.sh", 0o755)

    # 4. 実行パラメータの保存 (後段のPythonスクリプトでテンプレートを書き換えるため)
    with open("cfd_params.txt", "w") as f:
        f.write(f"VELOCITY={velocity}\n")
        f.write(f"MESH_LEVEL={mesh_level}\n")
        
        aero_stls_str = ",".join(aero_stls)
        f.write(f"AERO_STLS={aero_stls_str}\n")
        f.write(f"USE_TIRES={1 if use_tires else 0}\n")
        f.write(f"USE_FRAME={1 if use_frame else 0}\n")

    # 5. ホスト側で事前のファイル準備を行う
    print("\n[システム構築中... (Host-side preparation)]")
    for d in ['0', 'system', 'constant']:
        if os.path.exists(d):
            shutil.rmtree(d)
        shutil.copytree(f"template/{d}", d)
    
    # テンプレートの書き換え
    subprocess.run([sys.executable, "template/configure_templates.py"])

    print("\n設定が完了しました！")
    print("Dockerコンテナを起動し解析を開始します。これには時間がかかります。")
    print("--------------------------------------------------")

    if not args.no_docker:
        if os.environ.get("IN_DOCKER") == "1":
            print("\n==================================================")
            print("    Starting CFD Analysis inside Docker")
            print("==================================================")
            
            proc = subprocess.run(["bash", "-c", "./template/Allrun"])
            
            if proc.returncode == 0:
                os.makedirs("logs", exist_ok=True)
                for log_f in glob.glob("log.*"):
                    try:
                        shutil.move(log_f, os.path.join("logs", log_f))
                    except Exception:
                        pass
                
                subprocess.run([sys.executable, "extract_results.py"])
                
                print("\n[可視化画像・動画生成中...]")
                subprocess.run([sys.executable, "make_video.py"])
            else:
                print("解析中にエラーが発生しました。")
        else:
            # 従来通りホストからDockerを呼び出す場合 (互換性維持)
            env = os.environ.copy()
            env["PATH"] = env.get("PATH", "") + ":/usr/local/bin:/opt/homebrew/bin:/Applications/Docker.app/Contents/Resources/bin"
            
            proc = subprocess.run([
                "docker", "run", "--rm", 
                "-v", f"{os.getcwd()}:/data", 
                "opencfd/openfoam-default", 
                "bash", "-c", "cd /data && ./template/Allrun"
            ], env=env)
            
            # 6. ホスト側で結果を抽出
            if proc.returncode == 0:
                os.makedirs("logs", exist_ok=True)
                for log_f in glob.glob("log.*"):
                    try:
                        shutil.move(log_f, os.path.join("logs", log_f))
                    except Exception:
                        pass
                
                subprocess.run([sys.executable, "extract_results.py"])
                
                print("\n[可視化画像・動画生成中...]")
                subprocess.run([sys.executable, "make_video.py"])
            else:
                print("Docker実行中にエラーが発生しました。")
    else:
        print("[TEST MODE] Docker execution skipped.")

if __name__ == "__main__":
    main()
