import os
import sys
import glob
import subprocess

def get_float_input(prompt, default=None):
    while True:
        try:
            val = input(prompt)
            if not val and default is not None:
                return default
            return float(val)
        except ValueError:
            print("有効な数値を入力してください。")

def get_xyz_input(stl_name):
    print(f"\n--- {stl_name} の配置設定 ---")
    x = get_float_input(f"{stl_name} の X方向の移動量 (mm) [デフォルト: 0]: ", 0)
    y = get_float_input(f"{stl_name} の Y方向の移動量 (mm) [デフォルト: 0]: ", 0)
    z = get_float_input(f"{stl_name} の Z方向の移動量 (mm) [デフォルト: 0]: ", 0)
    return x, y, z

def main():
    print("==================================================")
    print("      FSAE 簡易CFDシステム Setup Wizard")
    print("==================================================")

    # 1. STLファイルの検出
    stl_files = [f for f in glob.glob("*.stl") if f.lower() != "tires.stl" and f.lower() != "frame.stl"]
    if not stl_files:
        print("エラー: カレントディレクトリに空力部品のSTLファイルが見つかりません。")
        print("body.stl などのファイルを配置してから再実行してください。")
        sys.exit(1)

    print("\n検出された空力部品STL:")
    for f in stl_files:
        print(f"  - {f}")

    # 2. 変数の取得
    velocity = get_float_input("\n解析する風速を入力してください (m/s) [デフォルト: 20]: ", 20.0)
    
    use_tires = input("計算にタイヤ (tires.stl) を含めますか？ (y/n) [デフォルト: y]: ").strip().lower() != 'n'
    if use_tires and not os.path.exists("tires.stl"):
        print("警告: tires.stl が見つかりません。タイヤなしで計算を進めます。")
        use_tires = False

    use_frame = input("フレーム等の非空力構造物 (frame.stl) を含めますか？ (y/n) [デフォルト: n]: ").strip().lower() == 'y'
    if use_frame and not os.path.exists("frame.stl"):
        print("警告: frame.stl が見つかりません。構造物なしで計算を進めます。")
        use_frame = False

    mesh_level = input("メッシュの細かさを選択してください (1:粗い 2:普通 3:細かい) [デフォルト: 2]: ").strip()
    if mesh_level not in ['1', '2', '3']:
        mesh_level = '2'

    clearance = get_float_input("\n全体のグラウンドクリアランス (Z方向の追加移動量 mm) を入力してください [デフォルト: 0]: ", 0)

    # 各STLのオフセット取得
    offsets = {}
    for stl in stl_files:
        offsets[stl] = get_xyz_input(stl)
    
    if use_tires:
        offsets["tires.stl"] = get_xyz_input("tires.stl")
    
    if use_frame:
        offsets["frame.stl"] = get_xyz_input("frame.stl")

    # 3. setup_stl.sh の生成
    # 単位はメートルに変換 (mm -> m)
    print("\n[システム構築中...]")
    with open("setup_stl.sh", "w") as f:
        f.write("#!/bin/sh\n")
        f.write("# This file is auto-generated by run_cfd.py\n\n")
        f.write("mkdir -p constant/triSurface\n\n")
        
        for stl, (x, y, z) in offsets.items():
            # クリアランスはZに加算してメートル変換
            z_total_m = (z + clearance) / 1000.0
            x_m = x / 1000.0
            y_m = y / 1000.0
            
            f.write(f"echo 'Processing {stl} ...'\n")
            f.write(f"surfaceTransformPoints -translate '({x_m} {y_m} {z_total_m})' ../{stl} constant/triSurface/{stl}\n\n")

    os.chmod("setup_stl.sh", 0o755)

    # 4. 実行パラメータの保存 (後段のPythonスクリプトでテンプレートを書き換えるため)
    with open("cfd_params.txt", "w") as f:
        f.write(f"VELOCITY={velocity}\n")
        f.write(f"MESH_LEVEL={mesh_level}\n")
        
        aero_stls = ",".join(stl_files)
        f.write(f"AERO_STLS={aero_stls}\n")
        f.write(f"USE_TIRES={1 if use_tires else 0}\n")
        f.write(f"USE_FRAME={1 if use_frame else 0}\n")

    print("\n設定が完了しました！")
    print("Dockerコンテナを起動し解析を開始します。これには時間がかかります。")
    print("--------------------------------------------------")

    # Dockerの起動
    # subprocess.run([
        "docker", "run", "--rm", 
        "-v", f"{os.getcwd()}:/data", 
        "-w", "/data", 
        "openfoam/openfoam-v2312-default", 
        "./template/Allrun"
    ])

if __name__ == "__main__":
    main()
