#!/bin/sh
# This file is auto-generated by run_cfd.py

mkdir -p constant/triSurface

echo 'Processing body.stl ...'
surfaceTransformPoints -translate '(0.0 0.0 0.0)' ./models/body.stl constant/triSurface/body.stl

echo 'Processing tires.stl ...'
surfaceTransformPoints -translate '(0.0 0.0 0.0)' ./models/tires.stl constant/triSurface/tires.stl

